/** Stable command identifiers contributed by API Hero. */
export const COMMAND_IDS = {
  runRequest: 'apiRunner.runRequest',
  runRequestWithAssertions: 'apiRunner.runRequestWithAssertions',
  runFile: 'apiRunner.runFile',
  login: 'apiRunner.login',
  logout: 'apiRunner.logout',
  switchEnvironment: 'apiRunner.switchEnvironment',
  manageEnvironments: 'apiRunner.manageEnvironments',
  manageAuthProfiles: 'apiRunner.manageAuthProfiles',
  selectAuthentication: 'apiRunner.selectAuthentication',
  refreshCollections: 'apiRunner.refreshCollections',
  filterCollections: 'apiRunner.filterCollections',
  revealActiveRequest: 'apiRunner.revealActiveRequest',
  openCollectionRequest: 'apiRunner.openCollectionRequest',
  focusCollections: 'apiRunner.focusCollections',
  runCollection: 'apiRunner.runCollection',
  runCollectionTests: 'apiRunner.runCollectionTests',
  runFolder: 'apiRunner.runFolder',
  runSelectedRequests: 'apiRunner.runSelectedRequests',
  focusHistory: 'apiRunner.focusHistory',
  openHistoryEntry: 'apiRunner.openHistoryEntry',
  rerunHistoryEntry: 'apiRunner.rerunHistoryEntry',
  deleteHistoryEntry: 'apiRunner.deleteHistoryEntry',
  clearHistory: 'apiRunner.clearHistory',
  searchHistory: 'apiRunner.searchHistory',
  refreshHistory: 'apiRunner.refreshHistory',
  revealHistoryRequest: 'apiRunner.revealHistoryRequest',
  copyHistorySummary: 'apiRunner.copyHistorySummary',
  importOpenApi: 'apiRunner.importOpenApi',
  createCollection: 'apiRunner.createCollection',
  renameCollection: 'apiRunner.renameCollection',
  deleteCollection: 'apiRunner.deleteCollection',
  duplicateCollection: 'apiRunner.duplicateCollection',
  exportCollection: 'apiRunner.exportCollection',
  importCollection: 'apiRunner.importCollection',
  createFolder: 'apiRunner.createFolder',
  renameFolder: 'apiRunner.renameFolder',
  deleteFolder: 'apiRunner.deleteFolder',
  duplicateFolder: 'apiRunner.duplicateFolder',
  createRequest: 'apiRunner.createRequest',
  renameRequest: 'apiRunner.renameRequest',
  duplicateRequest: 'apiRunner.duplicateRequest',
  deleteRequest: 'apiRunner.deleteRequest',
  moveRequest: 'apiRunner.moveRequest',
  openWorkspace: 'apiRunner.openWorkspace',
  openRequestEditor: 'apiRunner.openRequestEditor',
} as const;

/** A command identifier contributed by API Hero. */
export type CommandId = (typeof COMMAND_IDS)[keyof typeof COMMAND_IDS];
