/**
 * Unit tests for explicit source ↔ `.api` mapping (no VS Code).
 */

import assert from 'node:assert/strict';
import { test } from 'node:test';

import { requestIdFor } from '../collections';
import { COMMAND_IDS } from '../constants';
import {
  buildSourceIntegrationCatalog,
  catalogFromWorkspace,
  collidingGeneratedTypeNames,
  collectExportedTypeNames,
  createApiFileSourceCodeLensDescriptors,
  createSourceFileCodeLensDescriptors,
  formatRequestHover,
  parseSourceAnnotations,
  parseSourceDirectiveValue,
  prepareGeneratedTypeInsertion,
  sourcePathMatches,
  type CatalogRequest,
} from './index';
import type { Range } from '../parser/types';

function range(line: number): Range {
  return {
    start: { line, column: 0, offset: line * 10 },
    end: { line, column: 3, offset: line * 10 + 3 },
  };
}

function request(
  overrides: Partial<CatalogRequest> & Pick<CatalogRequest, 'id' | 'name'>,
): CatalogRequest {
  return {
    filePath: `file:///ws/Collections/Demo/${overrides.name.replace(/\s+/gu, '-')}.api`,
    relativePath: `Collections/Demo/${overrides.name.replace(/\s+/gu, '-')}.api`,
    workspaceRootPath: 'file:///ws',
    requestIndex: 0,
    method: 'GET',
    url: '/users',
    protocol: 'http',
    range: range(2),
    ...overrides,
  };
}

test('parses explicit @api-hero annotations and ignores unannotated calls', () => {
  const sites = parseSourceAnnotations(
    [
      '// @api-hero name: Get User',
      'const response = await api.getUser(id)',
      '',
      'const other = await api.listUsers()',
    ].join('\n'),
  );
  assert.equal(sites.length, 1);
  assert.equal(sites[0]?.line, 1);
  assert.deepEqual(sites[0]?.annotations, [
    { kind: 'name', value: 'Get User' },
  ]);
});

test('parses request path, JSDoc, and generated-file header annotations', () => {
  const sites = parseSourceAnnotations(
    [
      '/**',
      ' * Generated by API Hero.',
      ' * @api-hero name: Get User',
      ' * @api-hero request: Collections/Demo/Get-User.api',
      ' */',
      'export interface GetUser {}',
    ].join('\n'),
  );
  assert.equal(sites.length, 1);
  assert.equal(sites[0]?.line, 5);
  assert.equal(sites[0]?.annotations.length, 2);
  assert.equal(sites[0]?.annotations[0]?.kind, 'name');
  assert.equal(sites[0]?.annotations[1]?.kind, 'request');
});

test('bare .api path is a request annotation; bare text is a name', () => {
  const sites = parseSourceAnnotations(
    [
      '// @api-hero Collections/Demo/Get-User.api',
      'export const run = () => undefined',
      '// @api-hero Get User',
      'export const named = () => undefined',
    ].join('\n'),
  );
  assert.equal(sites[0]?.annotations[0]?.kind, 'request');
  assert.equal(sites[1]?.annotations[0]?.kind, 'name');
});

test('parses hash comments, camelCase JSDoc, and id annotations', () => {
  const sites = parseSourceAnnotations(
    [
      '# @api-hero name: Get User',
      'const fromHash = await api.getUser()',
      '/**',
      ' * @apiHero id: request:a#0',
      ' */',
      'export interface GetUser {}',
    ].join('\n'),
  );
  assert.equal(sites.length, 2);
  assert.deepEqual(sites[0]?.annotations, [{ kind: 'name', value: 'Get User' }]);
  assert.deepEqual(sites[1]?.annotations, [{ kind: 'id', value: 'request:a#0' }]);
});

test('CodeLens appears only for a uniquely matching API', () => {
  const catalog = buildSourceIntegrationCatalog([
    request({ id: 'request:a#0', name: 'Get User' }),
  ]);
  const lenses = createSourceFileCodeLensDescriptors(
    '// @api-hero Get User\nconst response = await api.getUser(id)\n',
    catalog,
    { sourceFilePath: 'file:///ws/src/user.ts', workspaceRoots: ['file:///ws'] },
  );
  assert.equal(lenses.length, 3);
  assert.equal(lenses[0]?.command.id, COMMAND_IDS.runRequest);
  assert.equal(lenses[1]?.command.id, COMMAND_IDS.openApiDefinition);
  assert.equal(lenses[2]?.command.id, COMMAND_IDS.generateTypeScript);
});

test('no CodeLens when there is no matching API', () => {
  const catalog = buildSourceIntegrationCatalog([
    request({ id: 'request:a#0', name: 'Get User' }),
  ]);
  const lenses = createSourceFileCodeLensDescriptors(
    '// @api-hero Missing\nconst response = await api.getUser(id)\n',
    catalog,
    { sourceFilePath: 'file:///ws/src/user.ts', workspaceRoots: ['file:///ws'] },
  );
  assert.deepEqual(lenses, []);
});

test('no CodeLens when multiple APIs share the same name', () => {
  const catalog = buildSourceIntegrationCatalog([
    request({
      id: 'request:a#0',
      name: 'Get User',
      filePath: 'file:///ws/Collections/A/Get-User.api',
      relativePath: 'Collections/A/Get-User.api',
    }),
    request({
      id: 'request:b#0',
      name: 'Get User',
      filePath: 'file:///ws/Collections/B/Get-User.api',
      relativePath: 'Collections/B/Get-User.api',
    }),
  ]);
  const lenses = createSourceFileCodeLensDescriptors(
    '// @api-hero Get User\nconst response = await api.getUser(id)\n',
    catalog,
    { sourceFilePath: 'file:///ws/src/user.ts', workspaceRoots: ['file:///ws'] },
  );
  assert.deepEqual(lenses, []);
});

test('renamed API drops name-based CodeLens and keeps path-based CodeLens', () => {
  const catalog = buildSourceIntegrationCatalog([
    request({
      id: 'request:a#0',
      name: 'Get User V2',
      relativePath: 'Collections/Demo/Get-User.api',
      filePath: 'file:///ws/Collections/Demo/Get-User.api',
    }),
  ]);
  const renamed = createSourceFileCodeLensDescriptors(
    '// @api-hero Get User\nconst response = await api.getUser(id)\n',
    catalog,
    { sourceFilePath: 'file:///ws/src/user.ts', workspaceRoots: ['file:///ws'] },
  );
  assert.deepEqual(renamed, []);

  const byPath = createSourceFileCodeLensDescriptors(
    '// @api-hero request: Collections/Demo/Get-User.api\nconst response = await api.getUser(id)\n',
    catalog,
    { sourceFilePath: 'file:///ws/src/user.ts', workspaceRoots: ['file:///ws'] },
  );
  assert.equal(byPath.length, 3);
});

test('deleted API produces no mapping', () => {
  const catalog = buildSourceIntegrationCatalog([]);
  const resolved = catalog.resolveFromAnnotations(
    [{ kind: 'name', value: 'Get User' }],
    { sourceFilePath: 'file:///ws/src/user.ts', workspaceRoots: ['file:///ws'] },
  );
  assert.equal(resolved.kind, 'none');
});

test('unsupported source without annotations has no CodeLens', () => {
  const catalog = buildSourceIntegrationCatalog([
    request({ id: 'request:a#0', name: 'Get User' }),
  ]);
  const lenses = createSourceFileCodeLensDescriptors(
    'const response = await api.getUser(id)\n',
    catalog,
    { sourceFilePath: 'file:///ws/src/user.ts', workspaceRoots: ['file:///ws'] },
  );
  assert.deepEqual(lenses, []);
});

test('multi-root: unique path maps; duplicate names across roots do not', () => {
  const catalog = buildSourceIntegrationCatalog([
    request({
      id: 'request:a#0',
      name: 'Health',
      workspaceRootPath: 'file:///ws-a',
      filePath: 'file:///ws-a/Collections/Demo/Health.api',
      relativePath: 'Collections/Demo/Health.api',
    }),
    request({
      id: 'request:b#0',
      name: 'Health',
      workspaceRootPath: 'file:///ws-b',
      filePath: 'file:///ws-b/Collections/Other/Health.api',
      relativePath: 'Collections/Other/Health.api',
    }),
  ]);
  const byName = catalog.resolveFromAnnotations(
    [{ kind: 'name', value: 'Health' }],
    {
      sourceFilePath: 'file:///ws-a/src/app.ts',
      workspaceRoots: ['file:///ws-a', 'file:///ws-b'],
    },
  );
  assert.equal(byName.kind, 'ambiguous');

  const byPath = catalog.resolveFromAnnotations(
    [{ kind: 'request', value: 'Collections/Demo/Health.api' }],
    {
      sourceFilePath: 'file:///ws-a/src/app.ts',
      workspaceRoots: ['file:///ws-a', 'file:///ws-b'],
    },
  );
  assert.equal(byPath.kind, 'match');
  if (byPath.kind === 'match') {
    assert.equal(byPath.request.id, 'request:a#0');
  }
});

test('path plus name disambiguates a multi-request .api file', () => {
  const catalog = buildSourceIntegrationCatalog([
    request({
      id: 'request:file#0',
      name: 'List Users',
      filePath: 'file:///ws/Collections/Demo/users.api',
      relativePath: 'Collections/Demo/users.api',
      requestIndex: 0,
    }),
    request({
      id: 'request:file#1',
      name: 'Get User',
      filePath: 'file:///ws/Collections/Demo/users.api',
      relativePath: 'Collections/Demo/users.api',
      requestIndex: 1,
      range: range(8),
    }),
  ]);
  const pathOnly = catalog.resolveFromAnnotations(
    [{ kind: 'request', value: 'Collections/Demo/users.api' }],
    { sourceFilePath: 'file:///ws/src/user.ts', workspaceRoots: ['file:///ws'] },
  );
  assert.equal(pathOnly.kind, 'ambiguous');

  const disambiguated = catalog.resolveFromAnnotations(
    [
      { kind: 'request', value: 'Collections/Demo/users.api' },
      { kind: 'name', value: 'Get User' },
    ],
    { sourceFilePath: 'file:///ws/src/user.ts', workspaceRoots: ['file:///ws'] },
  );
  assert.equal(disambiguated.kind, 'match');
  if (disambiguated.kind === 'match') {
    assert.equal(disambiguated.request.id, 'request:file#1');
  }
});

test('source → .api mapping uses the catalog request file path', () => {
  const mapped = request({ id: 'request:a#0', name: 'Get User' });
  const catalog = buildSourceIntegrationCatalog([mapped]);
  const resolved = catalog.resolveFromAnnotations(
    [{ kind: 'name', value: 'Get User' }],
    { sourceFilePath: 'file:///ws/src/user.ts', workspaceRoots: ['file:///ws'] },
  );
  assert.equal(resolved.kind, 'match');
  if (resolved.kind === 'match') {
    assert.equal(resolved.request.filePath, mapped.filePath);
  }
});

test('.api → source mapping uses authored @source only', () => {
  const withSource = request({
    id: 'request:a#0',
    name: 'Get User',
    sourceRef: 'src/services/user.ts:12',
  });
  const catalog = buildSourceIntegrationCatalog([withSource]);
  const hits = catalog.findRequestsForSourceFile('file:///ws/src/services/user.ts');
  assert.equal(hits.length, 1);
  assert.equal(hits[0]?.id, 'request:a#0');

  const missing = catalog.findRequestsForSourceFile('file:///ws/src/other.ts');
  assert.deepEqual(missing, []);
});

test('missing and stale source mappings do not invent a target', () => {
  assert.deepEqual(
    createApiFileSourceCodeLensDescriptors(
      request({ id: 'request:a#0', name: 'Get User' }),
    ),
    [],
  );
  assert.equal(
    parseSourceDirectiveValue('../outside.ts'),
    undefined,
  );
  const stale = parseSourceDirectiveValue('src/missing.ts:4');
  assert.equal(stale?.path, 'src/missing.ts');
  assert.equal(stale?.line, 3);
});

test('.api CodeLens opens related source only when @source is authored', () => {
  const mapped = request({
    id: 'request:a#0',
    name: 'Get User',
    sourceRef: 'src/services/user.ts:12',
  });
  const lenses = createApiFileSourceCodeLensDescriptors(mapped);
  assert.equal(lenses.length, 1);
  assert.equal(lenses[0]?.command.id, COMMAND_IDS.openRelatedSource);
  assert.equal(lenses[0]?.command.argument.uri, mapped.filePath);
  assert.equal(lenses[0]?.line, mapped.range.start.line);

  assert.deepEqual(
    createApiFileSourceCodeLensDescriptors(
      request({
        id: 'request:b#0',
        name: 'Broken',
        sourceRef: '../outside.ts',
      }),
    ),
    [],
  );
});

test('resolveFromApiLocation matches file path and request index', () => {
  const mapped = request({ id: 'request:a#0', name: 'Get User' });
  const catalog = buildSourceIntegrationCatalog([mapped]);
  assert.equal(
    catalog.resolveFromApiLocation(mapped.filePath, 0)?.id,
    'request:a#0',
  );
  assert.equal(catalog.resolveFromApiLocation(mapped.filePath, 1), undefined);
});

test('sourcePathMatches joins workspace roots and rejects parent segments', () => {
  assert.equal(
    sourcePathMatches(
      'src/services/user.ts',
      'file:///ws/src/services/user.ts',
      ['file:///ws'],
    ),
    true,
  );
  assert.equal(
    sourcePathMatches('src/services/user.ts', 'file:///ws/src/other.ts', [
      'file:///ws',
    ]),
    false,
  );
  assert.equal(parseSourceDirectiveValue('src/../secrets.ts'), undefined);
});

test('hover uses protocol metadata and does not expose secrets', () => {
  const hover = formatRequestHover(
    request({
      id: 'request:a#0',
      name: 'Get User',
      method: 'GET',
      url: '/users/1?access_token=super-secret-token',
      protocol: 'http',
      sourceRef: 'src/services/user.ts',
    }),
  );
  assert.equal(hover.title, 'GET /users/1');
  assert.match(hover.body, /Name: Get User/u);
  assert.match(hover.body, /Protocol: HTTP/u);
  assert.match(hover.body, /Source: src\/services\/user\.ts/u);
  assert.doesNotMatch(hover.body, /super-secret-token/u);
  assert.doesNotMatch(hover.title, /super-secret-token/u);
  assert.doesNotMatch(hover.body, /Authorization/u);

  const unlabeled = formatRequestHover(
    request({
      id: 'request:b#0',
      name: 'GET /users/1?access_token=super-secret-token',
      method: 'GET',
      url: '/users/1?access_token=super-secret-token',
    }),
  );
  assert.equal(unlabeled.title, 'GET /users/1');
  assert.match(unlabeled.body, /Name: GET \/users\/1$/mu);
  assert.doesNotMatch(unlabeled.body, /super-secret-token/u);
  assert.doesNotMatch(unlabeled.title, /access_token/u);

  const graphql = formatRequestHover(
    request({
      id: 'request:g#0',
      name: 'GetUser',
      method: 'POST',
      url: '/graphql',
      protocol: 'graphql',
    }),
  );
  assert.equal(graphql.title, 'POST /graphql');
  assert.match(graphql.body, /Protocol: GraphQL/u);
});

test('type insertion detects duplicate names and does not overwrite', () => {
  const existing = 'export interface User {\n  id: number;\n}\n';
  assert.deepEqual(collidingGeneratedTypeNames(['User'], existing), ['User']);
  assert.deepEqual(collidingGeneratedTypeNames(['Account'], existing), []);
  assert.ok(collectExportedTypeNames(existing).has('User'));
  const inserted = prepareGeneratedTypeInsertion(existing, 'export interface Account {}\n');
  assert.match(inserted, /export interface User/u);
  assert.match(inserted, /export interface Account/u);
  assert.equal(existing.includes('Account'), false);
});

test('open .api overlays keep stable request ids for id mapping', () => {
  const filePath = 'file:///ws/Collections/Demo/Get-User.api';
  const id = requestIdFor(filePath, 0);
  const catalog = catalogFromWorkspace(undefined, [
    {
      filePath,
      workspaceRootPath: 'file:///ws',
      relativePath: 'Collections/Demo/Get-User.api',
      text: '@name Get User\nGET /users\n',
    },
  ]);
  assert.equal(catalog.requests[0]?.id, id);
  const resolved = catalog.resolveFromAnnotations(
    [{ kind: 'id', value: id }],
    { sourceFilePath: 'file:///ws/src/user.ts', workspaceRoots: ['file:///ws'] },
  );
  assert.equal(resolved.kind, 'match');
  if (resolved.kind === 'match') {
    assert.equal(resolved.request.name, 'Get User');
  }
});
